### PR TITLE
Changed default launch view for all the tracks model in order to make…

### PR DESCRIPTION
**Pull request by vandanamandlik**
… it properly visible.

*Issue #, if available:*

*Description of changes:*
Changed default launch view for all the tracks model in order to make it properly visible in gazebo.
NOTE: This is just enhancement.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by timrobotson** [comment]
Why is this needed in the ROS2 version when it wasn't in ROS1?

**Comment by mm318** [comment]
Do we know if the ROS1 version of the sample app has the camera on the track at first launch?

**Comment by vandanamandlik** [comment]
> Do we know if the ROS1 version of the sample app has the camera on the track at first launch?
It doesn't launch actual camera. It's just name of the property in gazebo.
It will just set the default launch view instead of user requiring to manually adjust in order to look it better.
You can see that in attached image. (World->GUI->Property->Camera->Pose)

easy_track_view

**Comment by vandanamandlik** [comment]
> Why is this needed in the ROS2 version when it wasn't in ROS1?

Its not needed. but It will set the default launch view instead of user requiring to manually adjust in order to look it better.

If you see default launch view of ROS1 hard track, you have to change gazebo view to TOP view in order to make track and car properly visible.

With this change user doesn't have to adjust it manually.

**Comment by timrobotson** [comment]
> If you see default launch view of ROS1 hard track, you have to change gazebo view to TOP view in order to make track and car properly visible.
> 
> With this change user doesn't have to adjust it manually.

That makes sense. Would be good to explain that in the initial change in the future.

**Review by timrobotson — APPROVED** [review]

**Review by mm318 — APPROVED** [review]

**Pull request merged**
